# Generated by Django 4.0.5 on 2022-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_name_alter_recipe_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=32, verbose_name='Единица измерения'),
        ),
    ]
